name: CI/CD pipeline
on:
  push:
      branches:
        - master
  pull_request:
    branches:
      - master
permissions:
  contents: write

env:
  TAG_PREFIX: PDN
  APP_NAME: base-hexagonal
jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - name: Download the code
          uses: actions/checkout@v5.0.1
        - name: Set up java 25
          uses: actions/setup-java@v5.0.0
          with:
            distribution: 'corretto'
            java-version: '25'
        - name: Cache gradle dependencies
          uses: actions/cache@v4
          with:
            path: |
              ~/.gradle/caches
              ~/.gradle/wrapper
            key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle', '**/gradle-wrapper.properties') }}
            restore-keys: |
              ${{ runner.os }}-gradle-
        - name: Make gradlew executable
          run: chmod +x gradlew
        - name: Build with Gradle
          run: ./gradlew build
        - name: Upload JAR
          uses: actions/upload-artifact@v5.0.0
          with:
            name: app-jar
            path: infrastructure/entrypoints/build/libs/*.jar
  tag:
    runs-on: ubuntu-latest
    needs: build
    outputs:
      version: ${{ steps.tag.outputs.TAG }}
    steps:
        - name: Checkout repository
          uses: actions/checkout@v5.0.1
        - name: Generate TAG
          id: tag
          run: echo "TAG=${TAG_PREFIX}_$(date +'%Y%m%d')_${{ github.run_number }}" >> $GITHUB_OUTPUT
        - name: Create Git tag
          run: |
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git tag ${{ steps.tag.outputs.TAG }}
            git push origin ${{ steps.tag.outputs.TAG }}
  docker:
    runs-on: ubuntu-latest
    needs: tag
    steps:
        - name: Checkout reposiotry
          uses: actions/checkout@v5.0.1
        - name: Download JAR
          uses: actions/download-artifact@v5.0.0
          with:
            name: app-jar
            path: .
        - name: Log in to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        - name: Build Docker image
          run: |
            docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ env.APP_NAME }}:${{ needs.tag.outputs.version }}  .

        - name: Push Docker image
          run: |
            docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.APP_NAME }}:${{ needs.tag.outputs.version }} 
